version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Entered pre_build phase
      - npm install
  build:
    commands:
      - echo Entered build phase
      - npm test

  post_build:
    commands:
      - echo Entered post_build phase
      - npm version patch
      - npm publish
