version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Entered pre_build phase
      - aws codeartifact login --tool npm --repository my-team-repository --domain example-domain --domain-owner 849037323980 --region=eu-west-1 --namespace=gurra
      - npm install
  build:
    commands:
      - echo Entered build phase
      - npm test

  post_build:
    commands:
      - echo Entered post_build phase
      - npm publish
